### ISSUE TITLE
PC101 Issues

### ISSUE THREAD

**Issue by jpena176** [TonyMarfil/f5agility2020-pc101#1]
running section 1.4.2
needed to run terraform init before terraform validate

f5admin@EC2AMAZ-OQBMC1S:~/f5agility2020-pc101$ terraform validate

Error: Could not satisfy plugin requirements

Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".

Error: provider.local: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Error: provider.null: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Error: provider.template: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

1.4.3
need to add . in front of create-ssh-to-bigip-alias.sh in order to confirm the type command output

1.5.3
Update documentation for iApp config
Which region do you want to search for pool members - value=US West (Oregon) us-west-2

1.6.3
Update documentation to Ctrl + click on the Bigip1VipEipAddress (not BigIP1Url)

1.7.1
Could not delete the objects manually.  Deleted the iApp entries and everything was subsequently removed

**Comment by TonyMarfil** [comment]
Fixed. Thanks!
